CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE _permissions (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK__permissions" PRIMARY KEY ("ID"),
    CONSTRAINT "AK__permissions_Name" UNIQUE ("Name")
);

CREATE TABLE users (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("ID")
);

CREATE TABLE "PermissionUser" (
    "HoldersID" integer NOT NULL,
    "PermissionsID" integer NOT NULL,
    CONSTRAINT "PK_PermissionUser" PRIMARY KEY ("HoldersID", "PermissionsID"),
    CONSTRAINT "FK_PermissionUser__permissions_PermissionsID" FOREIGN KEY ("PermissionsID") REFERENCES _permissions ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_PermissionUser_users_HoldersID" FOREIGN KEY ("HoldersID") REFERENCES users ("ID") ON DELETE CASCADE
);

CREATE INDEX "IX_PermissionUser_PermissionsID" ON "PermissionUser" ("PermissionsID");

CREATE UNIQUE INDEX "IX_users_Username" ON users ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250216100816_Initial', '7.0.20');

COMMIT;

